from pathlib import Path

path = Path('src/pages/admin/AbsensiTab.tsx')
s = path.read_text(encoding='utf-8')
old = '''    useEffect(() => {\n        setLoading(true);\n        let q;\n        if (filterDateMode === 'all') {\n            q = query(collection(db, 'attendance'));\n        } else {\n            q = query(collection(db, 'attendance'), where('tanggal', '==', filterDate));\n        }\n        \n        const unsubAttendance = onSnapshot(q, (snap) => {\n            let data: any[] = [];\n            snap.forEach(doc => data.push({ id: doc.id, ...doc.data() }));\n\n            if (data.length === 0) {\n                data = [...DEFAULT_ATTENDANCE];\n            }\n\n            data.sort((a, b) => {\n                const dateComp = (b.tanggal || '').localeCompare(a.tanggal || '');\n                if (dateComp !== 0) return dateComp;\n                return (b.jam_masuk || '').localeCompare(a.jam_masuk || '');\n            });\n\n            if (filterDivisi) {\n                data = data.filter(item => {\n                    const user = getUserFromRecord(item, usersMap);\n                    return user.divisi === filterDivisi || item.divisi === filterDivisi;\n                });\n            }\n            \n            setAttendance(data);\n            setLoading(false);\n        }, (error) => {\n            console.warn("[AbsensiTab] Attendance sync notice, using fallbacks:", error?.message || error);\n            setAttendance(DEFAULT_ATTENDANCE);\n            setLoading(false);\n        });\n\n        return () => unsubAttendance();\n    }, [filterDate, filterDateMode, filterDivisi, usersMap]);'''
new = '''    useEffect(() => {\n        setLoading(true);\n\n        // Read the complete real attendance collection first, then filter in the\n        // client. This avoids a missing/incorrect Firestore query index or a\n        // legacy date-format mismatch hiding valid employee records.\n        const unsubAttendance = onSnapshot(collection(db, 'attendance'), (snap) => {\n            let data: any[] = [];\n            snap.forEach(docSnap => data.push({ id: docSnap.id, ...docSnap.data() }));\n\n            // Normalize date values so legacy records remain visible.\n            const normalizeDate = (value: any): string => {\n                if (!value) return '';\n                if (typeof value === 'string') return value.slice(0, 10);\n                if (value?.toDate) return format(value.toDate(), 'yyyy-MM-dd');\n                if (value instanceof Date) return format(value, 'yyyy-MM-dd');\n                return String(value).slice(0, 10);\n            };\n\n            if (filterDateMode !== 'all') {\n                data = data.filter(item => normalizeDate(item.tanggal) === filterDate);\n            }\n\n            data.sort((a, b) => {\n                const dateComp = normalizeDate(b.tanggal).localeCompare(normalizeDate(a.tanggal));\n                if (dateComp !== 0) return dateComp;\n                return (b.jam_masuk || '').localeCompare(a.jam_masuk || '');\n            });\n\n            if (filterDivisi) {\n                data = data.filter(item => {\n                    const user = getUserFromRecord(item, usersMap);\n                    return user.divisi === filterDivisi || item.divisi === filterDivisi;\n                });\n            }\n\n            // IMPORTANT: never replace real Firestore data with demo attendance.\n            // Empty means genuinely no records for the selected date.\n            setAttendance(data);\n            setLoading(false);\n        }, (error) => {\n            console.error('[AbsensiTab] Attendance sync error:', error?.message || error);\n            setAttendance([]);\n            setLoading(false);\n            toast.error('Gagal memuat data absensi dari server. Silakan coba lagi.');\n        });\n\n        return () => unsubAttendance();\n    }, [filterDate, filterDateMode, filterDivisi, usersMap]);'''
if old not in s:
    raise SystemExit('Expected daily attendance block not found; refusing modification.')
s = s.replace(old, new, 1)
path.write_text(s, encoding='utf-8')
print('Daily admin attendance now reads all Firestore records and filters client-side without demo fallback.')
